<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="FluentValidation" Version="12.1.1"/>
        <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageVersion Include="Mediator.Abstractions" Version="3.0.2"/>
        <PackageVersion Include="Mediator.SourceGenerator" Version="3.0.2"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.11"/>
        <PackageVersion Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.12"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11"/>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11"/>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageVersion Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556"/>
    </ItemGroup>
</Project>