<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
        <Content Remove="stylecop.json" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Components\Display\BoolDisplay.razor" />
        <AdditionalFiles Include="Components\Display\CountryName.razor" />
        <AdditionalFiles Include="Components\Display\SexDisplay.razor" />
        <AdditionalFiles Include="Components\Pages\DonationEvents\Create.razor" />
        <AdditionalFiles Include="Components\Pages\DonationEvents\Delete.razor" />
        <AdditionalFiles Include="Components\Pages\DonationEvents\List.razor" />
        <AdditionalFiles Include="Components\Pages\DonationEvents\Update.razor" />
        <AdditionalFiles Include="Components\Pages\Donors\Details.razor" />
        <AdditionalFiles Include="Components\Pages\Donors\UpdatePersonal.razor" />
        <AdditionalFiles Include="Components\Pages\Generic\List.razor" />
        <AdditionalFiles Include="Components\Pages\Generic\ListCore.razor" />
        <AdditionalFiles Include="Components\Pages\Locations\Create.razor" />
        <AdditionalFiles Include="Components\Pages\Locations\Delete.razor" />
        <AdditionalFiles Include="Components\Pages\Locations\List.razor" />
        <AdditionalFiles Include="Components\Pages\Locations\Update.razor" />
        <AdditionalFiles Include="Components\Pages\Municipalities\Create.razor" />
        <AdditionalFiles Include="Components\Pages\Municipalities\Delete.razor" />
        <AdditionalFiles Include="Components\Pages\Municipalities\List.razor" />
        <AdditionalFiles Include="Components\Pages\Municipalities\Update.razor" />
        <AdditionalFiles Include="Components\Shared\Pagination.razor" />
        <AdditionalFiles Include="Components\Validation\TemplatedValidationMessage.razor" />
        <AdditionalFiles Include="stylecop.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BSDSalzburg2024.Application\BSDSalzburg2024.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Auth\AuthStatus.razor" />
    </ItemGroup>

</Project>
