<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BSDSalzburg2024.Application.Contracts\BSDSalzburg2024.Application.Contracts.csproj" />
    <ProjectReference Include="..\BSDSalzburg2024.Domain\BSDSalzburg2024.Domain.csproj" />
  </ItemGroup>

</Project>
