<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BSDSalzburg2024.Application.Requests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
